server:
  port: 8001
spring:
  application:
    name: consul-student-service
  cloud:
    consul:
      port: 8500
      host: 127.0.0.1
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true

