server:
  port: 8003
spring:
  application:
    name: consul-student-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        # 不需要注册到consul中
        register: false
        prefer-ip-address: true